#!/usr/bin/env python3
"""Render the Leichhardt recipe collection without a browser data dependency."""
import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def esc(value):
    return html.escape(str(value), quote=True)


def render(data):
    cards = []
    for number, recipe in enumerate(data['recipes'], 1):
        components = []
        for component in recipe['components']:
            rows = ''.join(
                f'<tr><th scope="row">{esc(item)}</th><td>{esc(qty)}</td></tr>'
                for item, qty in component['ingredients']
            )
            components.append(
                f'<table class="lc-ingredients"><caption>{esc(component["name"])}</caption>'
                f'<tbody>{rows}</tbody></table>'
            )
        method = ''.join(f'<li>{esc(step)}</li>' for step in recipe['method'])
        points = ''.join(f'<li>{esc(point)}</li>' for point in recipe['key_points'])
        plating_note = f'<p class="lc-description" style="padding: .75rem 1.4rem">{esc(recipe["plating_note"])}</p>' if recipe.get('plating_note') else ''
        cards.append(f'''
      <article class="lc-recipe" id="{esc(recipe['id'])}" aria-labelledby="{esc(recipe['id'])}-title">
        <div class="lc-recipe-heading">
          <p class="lc-eyebrow">Dish {number} · {esc(recipe['yield'])}</p>
          <h3 id="{esc(recipe['id'])}-title">{esc(recipe['name'])}</h3>
          <p class="lc-subtitle">{esc(recipe['subtitle'])}</p>
          <p class="lc-description">{esc(recipe['description'])}</p>
        </div>
        <svg class="lc-plating" viewBox="{esc(recipe['plating_viewbox'])}" role="img" aria-label="{esc(recipe['plating_alt'])}">
          <image href="{esc(data['plating_sheet'])}" width="1024" height="1536" />
        </svg>
{plating_note}
        <details class="lc-details">
          <summary>Ingredients &amp; method<span class="lc-sr-only"> — {esc(recipe['name'])}</span></summary>
          <div class="lc-recipe-body">
            <h4>Ingredients ({esc(recipe['yield'])})</h4>
            {''.join(components)}
            <h4>Method</h4>
            <ol class="lc-method">{method}</ol>
            <h4>Key points</h4>
            <ul class="lc-points">{points}</ul>
          </div>
        </details>
      </article>''')
    return f'''<!DOCTYPE html>
<!-- Generated by scripts/build_leichhardt_page.py from leichhardt_data/cook_off.json. -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
  <meta name="theme-color" content="#0c0c0c">
  <meta name="description" content="Leichhardt cook-off recipes: crispy-skin barramundi and eye fillet, with component ingredients, methods and plating references.">
  <title>Leichhardt · Kuschi Kitchen</title>
  <link rel="manifest" href="manifest.webmanifest">
  <link rel="icon" href="icon-192.png">
  <link rel="apple-touch-icon" href="apple-touch-icon-180.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&amp;family=Inter:wght@300;400;500;600&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/theme.css?v=175">
  <link rel="stylesheet" href="assets/leichhardt.css">
  <script src="assets/kuschi-kitchen-mode.js"></script>
  <script src="assets/app-nav.js?v=3" defer></script>
</head>
<body class="has-app-nav leichhardt-page">
  <a class="lc-skip" href="#main">Skip to recipes</a>
  <main id="main" class="lc-shell">
    <header class="lc-header">
      <div><p class="lc-eyebrow">Kitchen recipes</p><h1>Leichhardt</h1></div>
      <a class="lc-button" href="{esc(data['pdf'])}?v={esc(data.get('revision', 1))}" download>Download one-page PDF</a>
    </header>
    <nav class="lc-sections" aria-label="Leichhardt sections">
      <a href="#cook-off" aria-current="location">Cook Off</a>
    </nav>
    <section id="cook-off" aria-labelledby="cook-off-title">
      <div class="lc-collection-heading">
        <div><h2 id="cook-off-title">Cook Off</h2><p>Trial dishes · 6 September 2026</p></div>
        <span class="lc-count">{len(cards)} recipes · 1 serve each</span>
      </div>
      <div class="lc-grid">{''.join(cards)}
      </div>
    </section>
    <footer class="lc-footer">Daniel Kuschmierz · <a href="index.html">Kitchen Library</a></footer>
  </main>
</body>
</html>
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check the published page matches its recipe source.')
    args = parser.parse_args()
    data = json.loads((ROOT / 'leichhardt_data/cook_off.json').read_text())
    ids = [recipe['id'] for recipe in data['recipes']]
    assert len(ids) == len(set(ids)), 'Recipe IDs must be unique'
    for asset in ('pdf', 'plating_sheet'):
        assert (ROOT / data[asset]).is_file(), f'Missing {asset}'
    output = ROOT / 'leichhardt.html'
    rendered = render(data)
    if args.check:
        if not output.exists() or output.read_text() != rendered:
            raise SystemExit('Leichhardt page is stale; run scripts/build_leichhardt_page.py')
        print('PASS Leichhardt page matches recipe source')
    else:
        output.write_text(rendered)
        print(f'Built {output.name}: {len(ids)} recipes')


if __name__ == '__main__':
    main()
