#!/usr/bin/env python3
"""One-off generator for assets/stocktake-data.js — run from repo root: python3 scripts/generate_riviera_stocktake_data.py"""
import json
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "stocktake-data.js"

# (name, brand, defaultQty, defaultUom, category) — zone from category map below
FREEZER_CATS = {
    "Pastry, bread, desserts",
    "Prepared/freezer portions",
    "Frozen savouries / convenience",
    "Frozen seafood and meats",
    "Frozen bread / gluten-free bakery",
}
COLD_CATS = {
    "Dairy, cheese, deli",
    "Fruit, veg, herbs",
    "Dips, sauces, condiments, oils",
}
DRY_CATS = {
    "Pantry, dry goods, rice, pasta, flour",
    "Spices, powders (volume estimates)",
    "Other spices / packets / pantry",
    "Crackers and snacks",
    "Chocolate / sweets",
}


def zone_for(cat):
    if cat in FREEZER_CATS:
        return "freezer"
    if cat in COLD_CATS:
        return "coldroom"
    if cat in DRY_CATS:
        return "drystore"
    raise ValueError(cat)


def prefix_for_zone(z):
    return {"freezer": "fr", "coldroom": "cr", "drystore": "ds"}[z]


def slug(s):
    s = re.sub(r"[^a-z0-9]+", "-", s.lower().strip())
    return s.strip("-")[:48] or "item"


# Raw rows: name, brand (empty = unknown/not stated), qty string, uom string, category
RAW = [
    # --- Freezer ---
    ("Puff Pastry Roll", "", "1", "roll", "Pastry, bread, desserts"),
    ("Puff Pastry Sheets", "Woolworths", "30", "sheets", "Pastry, bread, desserts"),
    ("Feta Pastry", "Antonio", "1", "box", "Pastry, bread, desserts"),
    ("Filo Pastry (Wrapped)", "", "3/4", "tray", "Pastry, bread, desserts"),
    ("Mini Croissants", "Sara Lee", "1/2", "box", "Pastry, bread, desserts"),
    ("Mini Brioche Slider Buns", "Laurent", "1/2", "box", "Pastry, bread, desserts"),
    ("Brioche Slider Buns", "KitKop", "1/4", "box", "Pastry, bread, desserts"),
    ("Cannoli Shells", "", "~45", "pc", "Pastry, bread, desserts"),
    ("Brownie", "", "3", "serves", "Pastry, bread, desserts"),
    ("Rum Balls", "", "5", "serves", "Pastry, bread, desserts"),
    ("Madeleine", "", "12", "serves", "Pastry, bread, desserts"),
    ("Gluten-Free Marble Cake Pastry", "", "12", "pieces", "Pastry, bread, desserts"),
    ("Raspberry Chocolate Gâteau (Vegan GF)", "Gourmet Delight", "7", "pieces", "Pastry, bread, desserts"),
    ("Vanilla Bean Ice Cream", "EV", "1", "tub", "Pastry, bread, desserts"),
    ("Birthday Cake Ice Cream", "Golden Gaytime", "3", "serves", "Pastry, bread, desserts"),
    ("Original Twin Pole", "Peters", "1", "box", "Pastry, bread, desserts"),
    ("Mini Ice Cream Cones (Raspberry or Strawberry)", "", "750", "mL", "Pastry, bread, desserts"),
    ("Choc Top Ice Cream", "Bulla", "2", "tubs (½ each)", "Pastry, bread, desserts"),
    ("Simply Vanilla Ice Cream", "Cold Rock", "1.8", "× 4 L tubs", "Pastry, bread, desserts"),
    ("Vanilla Ice Cream", "Woolworths", "1", "× 2 L tub", "Pastry, bread, desserts"),
    ("Artisan Italian Pistachio Gelati", "", "1", "tub", "Pastry, bread, desserts"),
    ("Lemon Lime Cheesecake", "", "1", "whole cake", "Pastry, bread, desserts"),
    ("Vanilla Cake with Biscoff", "Woolworths Bakery", "1.25", "cakes", "Pastry, bread, desserts"),
    ("Apple Pie (GF)", "Woolworths", "1", "whole", "Pastry, bread, desserts"),
    ("Gluten-Free Churros", "Wize", "1/2", "packet", "Pastry, bread, desserts"),
    ("Lamb Stock", "", "3", "L", "Prepared/freezer portions"),
    ("Apple Filling", "", "2", "L", "Prepared/freezer portions"),
    ("Lamb (Portions)", "", "4", "serves", "Prepared/freezer portions"),
    ("Chicken Skewers", "", "33", "serves", "Prepared/freezer portions"),
    ("Chorizo (Cut Up)", "", "15", "× 1 L containers", "Prepared/freezer portions"),
    ("Feta Cheese (Portions)", "", "16", "× 1 L containers", "Prepared/freezer portions"),
    ("Baba Ganoush", "", "3", "× 1 L containers", "Prepared/freezer portions"),
    ("Pulled Beef", "", "4", "× 1 L containers", "Prepared/freezer portions"),
    ("Diced Egg", "", "5", "× 500 mL containers", "Prepared/freezer portions"),
    ("Olive Stuffing", "", "2", "× 1 L containers", "Prepared/freezer portions"),
    ("Potato (Prepared)", "", "29", "serves", "Prepared/freezer portions"),
    ("Arancini", "", "5", "serves", "Prepared/freezer portions"),
    ("Fish (Portion)", "", "1", "serve", "Prepared/freezer portions"),
    ("Popcorn Cauliflower", "", "3", "serves", "Prepared/freezer portions"),
    ("Olives (Prepared)", "", "21", "serves", "Prepared/freezer portions"),
    ("Calamari (Prepared)", "", "26", "portions", "Prepared/freezer portions"),
    ("Halloumi (Portions)", "", "6", "portions", "Prepared/freezer portions"),
    ("Meatballs (Polpette)", "", "59", "portions", "Prepared/freezer portions"),
    ("Two-Bone Lamb Chops", "", "1", "tray (8 serves)", "Prepared/freezer portions"),
    ("Tzatziki (Frozen)", "", "3", "× 1 L containers", "Prepared/freezer portions"),
    ("Pulled Lamb in Red Wine", "", "4", "serves", "Prepared/freezer portions"),
    ("Bolognese", "", "9", "serves", "Prepared/freezer portions"),
    ("Angus Beef Sliders (Par-Cooked)", "Angel Bay", "1", "box", "Frozen savouries / convenience"),
    ("Homestyle Bacon Lasagna", "Helen's", "3/4", "box", "Frozen savouries / convenience"),
    ("Beef Party Pies", "Herbert Adams", "1", "box (12 pc)", "Frozen savouries / convenience"),
    ("Premium King Island Beef Sausage Rolls", "Herbert Adams", "1", "box", "Frozen savouries / convenience"),
    ("Quiche Lorraine", "VILI's", "124", "pieces", "Frozen savouries / convenience"),
    ("Sausage Rolls", "VILI's", "24", "pieces", "Frozen savouries / convenience"),
    ("Vegan Gluten Gourmet Roll", "ReadyBake", "4.2", "kg", "Frozen savouries / convenience"),
    ("Fish Bites (GF Crumb)", "Sea Lord", "1", "box (350 g)", "Frozen savouries / convenience"),
    ("Hoki Fish Bites", "Sealord", "1", "box", "Frozen savouries / convenience"),
    ("Spinach & Ricotta Patties", "", "24", "pieces (530 g)", "Frozen savouries / convenience"),
    ("Southern Style Tenders", "Melco Foods", "1", "carton (5 kg)", "Frozen savouries / convenience"),
    ("Beef Dim Sim", "Su Hin Dim Sum", "3/4", "box", "Frozen savouries / convenience"),
    ("Chicken Breast (GF)", "Ingham", "1", "box", "Frozen savouries / convenience"),
    ("Sausage Rolls (GF DF)", "", "4", "pieces", "Frozen savouries / convenience"),
    ("Pies", "", "9", "pies", "Frozen savouries / convenience"),
    ("Strawberries (Frozen)", "Caterer's Choice", "1", "kg", "Frozen seafood and meats"),
    ("Carvery Beef (Cooked)", "Naturalaz", "2", "packs (~4.905 kg one)", "Frozen seafood and meats"),
    ("Lamb Leg Roast (Boneless)", "Woolworths", "8", "pieces (~1.37 kg ea)", "Frozen seafood and meats"),
    ("Cooked Aussie Tiger Prawns", "Tassal", "1", "whole box", "Frozen seafood and meats"),
    ("Baby Octopus (Cleaned)", "", "19", "kg", "Frozen seafood and meats"),
    ("Wild Caught Reef Fish", "Seacrest", "2.5", "kg", "Frozen seafood and meats"),
    ("Squid Strips (Pineapple Cut)", "Seafrost", "6.5", "kg", "Frozen seafood and meats"),
    ("Greek-Style Lamb Meat (Frozen)", "Specialty Foods", "2", "kg", "Frozen seafood and meats"),
    ("Pork Belly", "SunPork Fresh Foods, Barker Creek", "3", "serves", "Frozen seafood and meats"),
    ("Pork Belly (Frozen)", "Naturalaz", "2", "pieces (2.8 & 2.9 kg)", "Frozen seafood and meats"),
    ("Beef Cheeks (Frozen)", "Jeffries", "2", "packs", "Frozen seafood and meats"),
    ("White Bread Toast", "", "2", "baker's trays", "Frozen bread / gluten-free bakery"),
    ("Pizza Bread", "Alfina's", "10", "portions", "Frozen bread / gluten-free bakery"),
    ("Soft White Half Loaf (GF)", "Tip Top Bakery", "1", "loaf", "Frozen bread / gluten-free bakery"),
    ("Turkish Bread (GF)", "Woolworths", "4", "loaves", "Frozen bread / gluten-free bakery"),
    ("Brioche-Style GF Burger Buns", "Woolworths", "2", "pieces", "Frozen bread / gluten-free bakery"),
    ("White Burger Buns (GF, Non-Brioche)", "Woolworths", "2", "packs of 4", "Frozen bread / gluten-free bakery"),
    ("GF Garlic and Herb Focaccia", "Senza", "1", "pack", "Frozen bread / gluten-free bakery"),
    ("GF Focaccia", "Community Co", "1", "pack (3 pc)", "Frozen bread / gluten-free bakery"),
    ("GF High-Fibre White Rolls", "Lifestyle Bakery", "1", "pack", "Frozen bread / gluten-free bakery"),
    ("Soft White Bread (GF)", "Woolworths", "1/2", "loaf", "Frozen bread / gluten-free bakery"),
    ("English Muffins (GF)", "Coles", "2", "muffins", "Frozen bread / gluten-free bakery"),
    ("Smoked Ham & Tasty Cheese Toasties (GF)", "", "5", "total", "Frozen bread / gluten-free bakery"),
    ("White Bread (Wheat/Dairy Free GF)", "Coles", "1", "loaf", "Frozen bread / gluten-free bakery"),
    ("Pizza Bases 12 inch (GF)", "Letizza", "1", "box", "Frozen bread / gluten-free bakery"),
    ("Greek Pitta Bread", "Golden Top Bakery", "4", "packs", "Frozen bread / gluten-free bakery"),
    ("GF Pita Breads", "BFree", "1.5", "packs", "Frozen bread / gluten-free bakery"),
    ("All-Butter Croissants (GF)", "Woolworths", "1", "pack of 2", "Frozen bread / gluten-free bakery"),
    ("Flour Tortillas 6 inch", "", "3", "packs (36 total)", "Frozen bread / gluten-free bakery"),
    ("Bread Rolls", "", "1", "bag", "Frozen bread / gluten-free bakery"),
    ("Roasted Sweet Potatoes", "Charworks Vegetables", "1.5", "boxes", "Frozen bread / gluten-free bakery"),
    ("Chopped Onion", "Edgell", "1", "box (~4–5 kg)", "Frozen bread / gluten-free bakery"),
    ("Frozen Egg Yolks", "Sunny Queen", "1", "box", "Frozen bread / gluten-free bakery"),
    # --- Cold room ---
    ("Coffee Chocolate Cream", "", "1", "L", "Dairy, cheese, deli"),
    ("Natural Greek Style Yogurt", "Woolworths", "2", "kg", "Dairy, cheese, deli"),
    ("Greek Style Yogurt", "Kalos", "1.8", "kg", "Dairy, cheese, deli"),
    ("Feta Cheese Block", "Yarde Farm", "2", "× 2 kg", "Dairy, cheese, deli"),
    ("Thickened Cream", "Woolworths", "3", "× 600 mL", "Dairy, cheese, deli"),
    ("Thickened Cream", "Black & Gold", "1", "× 600 mL", "Dairy, cheese, deli"),
    ("Halloumi", "", "3", "pieces", "Dairy, cheese, deli"),
    ("Tasty Cheese Slices", "Woolworths", "500", "g", "Dairy, cheese, deli"),
    ("Extra Tasty Aged Cheddar", "Mainland", "250", "g", "Dairy, cheese, deli"),
    ("Nuttelex Original", "Nuttelex", "500", "g", "Dairy, cheese, deli"),
    ("Mozzarella (Shredded)", "Hillsview", "700", "g", "Dairy, cheese, deli"),
    ("Natural Sliced Cheddar", "Dairyworks", "½", "pack", "Dairy, cheese, deli"),
    ("Mozzarella Cheese", "Woolworths", "350", "g", "Dairy, cheese, deli"),
    ("Parmesan Cheese", "Woolworths", "250", "g", "Dairy, cheese, deli"),
    ("Double Cream Brie", "Castello", "4", "serves", "Dairy, cheese, deli"),
    ("Mascarpone", "Woolworths", "250", "g", "Dairy, cheese, deli"),
    ("Mascarpone", "La Casa del Formaggio", "4", "× 250 g", "Dairy, cheese, deli"),
    ("Mascarpone", "Valesco Fresh", "1", "kg tub (½)", "Dairy, cheese, deli"),
    ("Mascarpone", "Tatua", "250", "g", "Dairy, cheese, deli"),
    ("Serrano Ham", "Redondo Iglesias", "½", "package", "Dairy, cheese, deli"),
    ("Prosciutto Sliced", "Don", "500", "g", "Dairy, cheese, deli"),
    ("Australian Prosciutto", "Mondelli", "2", "× 80 g", "Dairy, cheese, deli"),
    ("Prosciutto (Extra Packets)", "", "2", "packets", "Dairy, cheese, deli"),
    ("Authentic Spanish Style Chorizo", "Montecatini", "4", "packets", "Dairy, cheese, deli"),
    ("Sun-Dried Tomato Ham", "Woolworths", "500", "g", "Dairy, cheese, deli"),
    ("Australian Leg Ham", "Mondelli", "2", "× 100 g", "Dairy, cheese, deli"),
    ("Eggs", "Woolworths", "70", "eggs", "Dairy, cheese, deli"),
    ("Cucumber", "", "2", "pc", "Fruit, veg, herbs"),
    ("Sourdough Bread", "", "1", "loaf", "Fruit, veg, herbs"),
    ("Black Grapes", "", "1", "bag (~500–600 g)", "Fruit, veg, herbs"),
    ("Red Grapes", "", "4", "bags", "Fruit, veg, herbs"),
    ("Lemons", "", "~1.5", "kg", "Fruit, veg, herbs"),
    ("Oranges", "", "~1.5", "kg", "Fruit, veg, herbs"),
    ("Lime", "", "1.2", "kg", "Fruit, veg, herbs"),
    ("Tomatoes", "", "1.5", "kg", "Fruit, veg, herbs"),
    ("Red Onions", "", "500", "g", "Fruit, veg, herbs"),
    ("Brown Onions", "", "1.5", "kg", "Fruit, veg, herbs"),
    ("Garlic", "", "1.5", "kg", "Fruit, veg, herbs"),
    ("Confit Garlic", "", "1", "kg", "Fruit, veg, herbs"),
    ("Lemon Zest (Marinated)", "", "100", "mL", "Fruit, veg, herbs"),
    ("Lemon Zest (Extra)", "", "50", "g", "Fruit, veg, herbs"),
    ("Thyme (Loose)", "", "250", "mL", "Fruit, veg, herbs"),
    ("Pumpkin Seeds", "", "600", "mL", "Fruit, veg, herbs"),
    ("Mint", "Doblo", "5", "bunches", "Fruit, veg, herbs"),
    ("Spring Onion", "Doblo", "2", "bunches", "Fruit, veg, herbs"),
    ("Thyme", "Doblo", "5", "bags", "Fruit, veg, herbs"),
    ("Fresh Dill", "Doblo", "2", "bags", "Fruit, veg, herbs"),
    ("Flat Leaf Parsley", "Doblo", "2", "bags", "Fruit, veg, herbs"),
    ("Curly Parsley", "Doblo", "2", "bags", "Fruit, veg, herbs"),
    ("Fresh Oregano", "Doblo", "2", "bags", "Fruit, veg, herbs"),
    ("Bean Sprouts", "", "3", "bunches/packets", "Fruit, veg, herbs"),
    ("Lime Leaves", "", "20", "g", "Fruit, veg, herbs"),
    ("Rocket Baby Leaf", "Woolworths", "5", "× 120 g packs", "Fruit, veg, herbs"),
    ("Spicy Capsicum & Feta Dip", "Casa di Mare", "~1", "kg", "Dips, sauces, condiments, oils"),
    ("Jalapeños", "Riviana", "1", "large tin", "Dips, sauces, condiments, oils"),
    ("Tomato Paste", "", "2", "L", "Dips, sauces, condiments, oils"),
    ("Crushed Garlic", "", "500", "mL", "Dips, sauces, condiments, oils"),
    ("Romesco", "", "1", "L", "Dips, sauces, condiments, oils"),
    ("Hot Honey", "", "1.5", "L", "Dips, sauces, condiments, oils"),
    ("Aioli", "", "1", "L", "Dips, sauces, condiments, oils"),
    ("Tzatziki", "", "2.5", "L", "Dips, sauces, condiments, oils"),
    ("House Emulsion", "House made", "6", "L", "Dips, sauces, condiments, oils"),
    ("Orange Cinnamon Honey", "", "2", "L", "Dips, sauces, condiments, oils"),
    ("Couscous", "", "1", "L", "Dips, sauces, condiments, oils"),
    ("Sliced Shallots", "", "½", "bin (~1 L / 150 g)", "Dips, sauces, condiments, oils"),
    ("Whole Egg Mayonnaise", "S&W", "~440", "g", "Dips, sauces, condiments, oils"),
    ("Traditional Mayonnaise (GF)", "Woolworths", "470", "g", "Dips, sauces, condiments, oils"),
    ("Premium Mayonnaise", "Bega", "2", "kg", "Dips, sauces, condiments, oils"),
    ("Marinated Pitted Whole Olives", "Sandhurst", "10", "L bucket (~5 kg)", "Dips, sauces, condiments, oils"),
    ("Pitted Green Olives", "Sandhurst", "2", "× 350 g jars", "Dips, sauces, condiments, oils"),
    ("Marinated Olives", "", "2", "× 1 L containers", "Dips, sauces, condiments, oils"),
    ("Peppercorns", "Sandhurst", "120", "g", "Dips, sauces, condiments, oils"),
    ("Chargrilled Eggplant", "Casa di Mare", "1.9", "kg", "Dips, sauces, condiments, oils"),
    ("Baby Capers", "Casa di Mare", "2", "× 700 g", "Dips, sauces, condiments, oils"),
    ("Caramelized Onions", "Beerenberg", "1", "kg", "Dips, sauces, condiments, oils"),
    ("Concentrated Liquid Chicken Stock", "Knorr Professional", "1.25", "kg", "Dips, sauces, condiments, oils"),
    ("Caramel Syrup", "Cottee's", "3", "L", "Dips, sauces, condiments, oils"),
    ("Strawberry Syrup", "Cottee's", "3", "L", "Dips, sauces, condiments, oils"),
    ("Chocolate Flavoured Syrup", "Cottee's", "1.5", "L", "Dips, sauces, condiments, oils"),
    ("Chocolate Flavoured Topping", "Woolworths Essentials", "600", "mL", "Dips, sauces, condiments, oils"),
    ("Lime Juice", "Woolworths", "2", "L", "Dips, sauces, condiments, oils"),
    ("Lemon Juice", "Lovely Lemon", "500", "mL", "Dips, sauces, condiments, oils"),
    ("Orange Juice", "Daily Juice", "2", "L", "Dips, sauces, condiments, oils"),
    ("Basil Purée", "New Fresh Farmers", "160", "g", "Dips, sauces, condiments, oils"),
    ("Worcestershire Sauce", "Woolworths", "250", "mL", "Dips, sauces, condiments, oils"),
    ("Worcestershire Sauce", "Sunshine", "6", "L total", "Dips, sauces, condiments, oils"),
    ("Crispy Chili Oil", "", "210", "g", "Dips, sauces, condiments, oils"),
    ("Balsamic Glaze", "Coles", "100", "g", "Dips, sauces, condiments, oils"),
    ("Balsamic Glaze", "Woolworths", "100", "mL", "Dips, sauces, condiments, oils"),
    ("Sweet Mustard Pickles", "333", "250", "g", "Dips, sauces, condiments, oils"),
    ("Dijon Mustard Vinaigrette", "Praise", "250", "mL", "Dips, sauces, condiments, oils"),
    ("Honey Mustard Dressing Sauce", "Virgin Wade", "100", "mL", "Dips, sauces, condiments, oils"),
    ("Seafood Sauce", "Praise", "100", "g", "Dips, sauces, condiments, oils"),
    ("Chipotle Aioli", "Praise", "125", "mL", "Dips, sauces, condiments, oils"),
    ("Fish Sauce", "Squid Brand", "¾", "× 500 mL bottle", "Dips, sauces, condiments, oils"),
    ("Tabasco", "", "150", "mL (¾ full)", "Dips, sauces, condiments, oils"),
    ("Soy Milk", "So Good", "750", "mL", "Dips, sauces, condiments, oils"),
    ("Soy Milk", "Vitasoy", "750", "mL", "Dips, sauces, condiments, oils"),
    ("Light White Fresh Milk", "Dairy Farmers", "1", "L", "Dips, sauces, condiments, oils"),
    ("Lemon Juice", "Caterer's Choice", "½", "× 2 L bottle", "Dips, sauces, condiments, oils"),
    ("Honey Mustard Sauce", "French Maid", "2.5", "× 2 L bottles", "Dips, sauces, condiments, oils"),
    ("Hickory Smoked Barbecue Sauce", "Sunshine", "500", "mL", "Dips, sauces, condiments, oils"),
    ("Chipotle Barbecue Sauce", "Praise", "2", "kg", "Dips, sauces, condiments, oils"),
    ("Peri-Peri Sauce", "Praise", "2.5", "bottles (1.95 kg ea)", "Dips, sauces, condiments, oils"),
    ("Burger Sauce", "Wombat Valley", "500", "g", "Dips, sauces, condiments, oils"),
    ("Aioli", "Jeffries", "2", "× 1 L bottles", "Dips, sauces, condiments, oils"),
    ("Mango Habanero Sauce", "French Maid", "750", "mL", "Dips, sauces, condiments, oils"),
    ("Roasted Truffle Mayonnaise", "Virgin Wade", "", "qty n/s", "Dips, sauces, condiments, oils"),
    ("Mild Chunky Salsa", "Edlyn", "1", "kg", "Dips, sauces, condiments, oils"),
    ("Mild Chunky Tomato Salsa", "Woolworths", "300", "g", "Dips, sauces, condiments, oils"),
    ("Balsamic Dressing", "Bega", "2.6", "kg", "Dips, sauces, condiments, oils"),
    ("Seeded Mustard", "MasterFoods", "2.5", "kg", "Dips, sauces, condiments, oils"),
    ("Dijon Mustard", "MasterFoods", "1.5", "kg", "Dips, sauces, condiments, oils"),
    ("Tomato Sauce", "Caterer's Choice", "3", "L", "Dips, sauces, condiments, oils"),
    ("Barbecue Sauce", "Caterer's Choice", "3", "L", "Dips, sauces, condiments, oils"),
    ("Kewpie Mayo", "Kewpie", "7", "× ~1 kg bottles", "Dips, sauces, condiments, oils"),
    ("Portion Honey", "", "1", "box", "Dips, sauces, condiments, oils"),
    ("Strawberry & Rhubarb Jam", "St. Dalfour", "1", "jar", "Dips, sauces, condiments, oils"),
    ("Fig Royale Jam", "St. Dalfour", "1", "jar", "Dips, sauces, condiments, oils"),
    ("Cherry Jam", "Baraka's", "455", "g", "Dips, sauces, condiments, oils"),
    ("Raspberry Conserve", "Bonne Maman", "½", "× 370 g", "Dips, sauces, condiments, oils"),
    ("Jellied Cranberry Sauce", "Ocean Spray", "275", "g", "Dips, sauces, condiments, oils"),
    ("Cranberry Sauce", "Woolworths", "2", "× 275 g", "Dips, sauces, condiments, oils"),
    ("Maple Syrup", "Sunshine", "2", "L", "Dips, sauces, condiments, oils"),
    ("Maple Syrup", "Queen", "750", "mL", "Dips, sauces, condiments, oils"),
    ("Maple Flavoured Syrup", "Woolworths", "300", "g", "Dips, sauces, condiments, oils"),
    ("Maple Flavoured Syrup", "Edlyn", "~2", "L remaining", "Dips, sauces, condiments, oils"),
    ("White Wine Cooking Wine", "Caterer's Choice", "~10", "L", "Dips, sauces, condiments, oils"),
    ("Red Wine Cooking Wine", "Caterer's Choice", "~8", "L", "Dips, sauces, condiments, oils"),
    ("Old Tawny Port", "De Bortoli Premium", "4", "L", "Dips, sauces, condiments, oils"),
    ("Extra Virgin Olive Oil", "Sandhurst", "8", "L", "Dips, sauces, condiments, oils"),
    ("White Wine Vinegar", "Sandhurst", "~2", "L", "Dips, sauces, condiments, oils"),
    ("Red Wine Vinegar", "Sandhurst", "~6", "L total", "Dips, sauces, condiments, oils"),
    ("White Wine Vinegar", "Woolworths", "250", "mL", "Dips, sauces, condiments, oils"),
    ("White Vinegar", "Woolworths Essentials", "1", "L", "Dips, sauces, condiments, oils"),
    ("Apple Cider Vinegar", "Cornwell's", "500", "mL", "Dips, sauces, condiments, oils"),
    ("Lemon Infused EVOO", "Cobram", "3", "× 250 mL", "Dips, sauces, condiments, oils"),
    ("Truffle Infused Oil", "Cobram", "200", "mL", "Dips, sauces, condiments, oils"),
    ("Cooking Sake", "", "150", "mL", "Dips, sauces, condiments, oils"),
    ("Pure Sesame Oil", "Mr Chen's", "250", "mL", "Dips, sauces, condiments, oils"),
    ("Zesty Lemon & Herb Sauce", "MasterFoods", "250", "mL", "Dips, sauces, condiments, oils"),
    ("Balsamic Roasted Garlic", "Praise", "250", "mL", "Dips, sauces, condiments, oils"),
    ("Moro Italian Glaze", "Moro", "100", "mL", "Dips, sauces, condiments, oils"),
    ("Italian Glaze", "Knorr", "400", "g", "Dips, sauces, condiments, oils"),
    # Dry store
    ("Semolina", "Caterer's Choice", "1", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Fettuccine", "La Molisana", "500", "g", "Pantry, dry goods, rice, pasta, flour"),
    ("Basmati Rice", "SunRice", "1", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Arborio Rice", "Riviana", "5", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Italian Passata", "Coles", "1.4", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Sugo per Pasta", "Buitoni", "3", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Roasted Peppers", "Casa di Mare", "4.1", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Chickpea Flour", "McKenzie's", "660", "g total", "Pantry, dry goods, rice, pasta, flour"),
    ("Rice Flour (Coarse)", "Caterer's Choice", "4", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Self-Raising Flour", "Caterer's Choice", "~4", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Plain Flour", "Caterer's Choice", "10", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Crème Pâtissière", "Nestlé", "<½", "× 2 kg bucket", "Pantry, dry goods, rice, pasta, flour"),
    ("French Vanilla Flavour Mousse Mix", "Dolcello Nestlé", "900", "g (½)", "Pantry, dry goods, rice, pasta, flour"),
    ("Frying Shortening", "Red Band", "12.5", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Moroccan Seasoning", "MasterFoods", "1.5", "kg", "Pantry, dry goods, rice, pasta, flour"),
    ("Corn Flour", "", "3.9", "kg (7 L est.)", "Spices, powders (volume estimates)"),
    ("Rice Flour", "", "2.7", "kg (4.5 L est.)", "Spices, powders (volume estimates)"),
    ("Breadcrumbs", "", "600", "g (2 L est.)", "Spices, powders (volume estimates)"),
    ("Calamari Flour Mix", "House mix", "275", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Tapioca Starch", "", "1.65", "kg (3 L est.)", "Spices, powders (volume estimates)"),
    ("Spelt Flour", "", "800", "g (1.5 L est.)", "Spices, powders (volume estimates)"),
    ("GF Pizza Flour", "", "250", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("GF Normal Flour", "", "1", "kg (2 L est.)", "Spices, powders (volume estimates)"),
    ("Professional Dried Potatoes", "", "2", "kg (5 L est.)", "Spices, powders (volume estimates)"),
    ("Freeze-Dried Raspberries", "", "25", "g (200 mL est.)", "Spices, powders (volume estimates)"),
    ("White Chocolate Powder", "", "275", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Coconut Milk Powder", "", "1", "kg (2 L est.)", "Spices, powders (volume estimates)"),
    ("Lemon Pepper", "", "1", "kg (2 L est.)", "Spices, powders (volume estimates)"),
    ("Oregano (Bulk)", "", "600", "g (4 L est.)", "Spices, powders (volume estimates)"),
    ("Mixed Herbs", "", "375", "g (2.5 L est.)", "Spices, powders (volume estimates)"),
    ("Parsley (Dried Bulk)", "", "300", "g (2.5 L est.)", "Spices, powders (volume estimates)"),
    ("Fine Cracked Pepper", "MasterFoods?", "120", "g (200 mL est.)", "Spices, powders (volume estimates)"),
    ("Turmeric", "Krio", "400", "g (750 mL est.)", "Spices, powders (volume estimates)"),
    ("Ground Coriander", "Krio", "70", "g (150 mL est.)", "Spices, powders (volume estimates)"),
    ("Thyme (Dried Bulk)", "Krio", "35", "g (150 mL est.)", "Spices, powders (volume estimates)"),
    ("Dill (Dried)", "", "25", "g (150 mL est.)", "Spices, powders (volume estimates)"),
    ("Black Sesame Seeds", "Krio", "325", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Dukkah Mix", "Krio", "~250", "g combined", "Spices, powders (volume estimates)"),
    ("Mild Curry Powder", "Clive's", "400", "g (750 mL est.)", "Spices, powders (volume estimates)"),
    ("Cracked Black Pepper", "", "500", "g (850 mL est.)", "Spices, powders (volume estimates)"),
    ("Ground Black Pepper", "", "1", "kg (2 L est.)", "Spices, powders (volume estimates)"),
    ("MSG", "", "350", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Garlic Powder", "Trump", "550", "g (1 L est.)", "Spices, powders (volume estimates)"),
    ("Chicken Salt", "", "2.1", "kg (3 L est.)", "Spices, powders (volume estimates)"),
    ("Table Salt", "", "6", "kg (5 L est.)", "Spices, powders (volume estimates)"),
    ("Sugar Pearls", "", "425", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Pitted Dates", "", "1.3", "kg (2 L est.)", "Spices, powders (volume estimates)"),
    ("Desiccated Coconut", "", "1.7", "kg (4.5 L est.)", "Spices, powders (volume estimates)"),
    ("Custard Powder", "", "275", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Gelatine Powder", "", "325", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Baking Powder", "", "450", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Vanilla Sugar", "", "400", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Walnuts", "", "50", "g (100 mL est.)", "Spices, powders (volume estimates)"),
    ("Pistachios (Shelled)", "", "240", "g (400 mL est.)", "Spices, powders (volume estimates)"),
    ("Toasted Pepitas", "", "65", "g (100 mL est.)", "Spices, powders (volume estimates)"),
    ("Dehydrated Oranges", "", "240", "g (2 L est.)", "Spices, powders (volume estimates)"),
    ("Pistachios (Shell On)", "", "280", "g (700 mL est.)", "Spices, powders (volume estimates)"),
    ("Dehydrated Lemons", "", "18", "g (150 mL est.)", "Spices, powders (volume estimates)"),
    ("Shredded Coconut", "", "450", "g (1.5 L est.)", "Spices, powders (volume estimates)"),
    ("Ground Cinnamon", "", "560", "g (1.25 L est.)", "Spices, powders (volume estimates)"),
    ("Raw Sugar", "", "1.06", "kg (1.25 L est.)", "Spices, powders (volume estimates)"),
    ("Almond Sticks", "", "450", "g (1 L est.)", "Spices, powders (volume estimates)"),
    ("White Sesame Seeds", "", "780", "g (1.2 L est.)", "Spices, powders (volume estimates)"),
    ("Icing Sugar", "", "280", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Dry Yeast", "", "250", "g (500 mL est.)", "Spices, powders (volume estimates)"),
    ("Coffee Sugar", "", "170", "g (200 mL est.)", "Spices, powders (volume estimates)"),
    ("Brown Sugar", "", "140", "g (200 mL est.)", "Spices, powders (volume estimates)"),
    ("Caster Sugar", "", "3.1", "kg (3.6 L est.)", "Spices, powders (volume estimates)"),
    ("Persian Fairy Floss (Pistachio)", "Pariya", "200", "g", "Other spices / packets / pantry"),
    ("Rose Petals", "Herbie Spices", "5", "g", "Other spices / packets / pantry"),
    ("Crystallized Ginger", "Buderim", "200", "g", "Other spices / packets / pantry"),
    ("Finest Cranberry", "Angas Park", "40", "g", "Other spices / packets / pantry"),
    ("French Onion Soup", "Woolworths", "3", "× 40 g", "Other spices / packets / pantry"),
    ("Maggi Jus Beef Flavoured Sauce Mix", "", "1.8", "kg", "Other spices / packets / pantry"),
    ("Maggi Vegetable Sauce Powder", "", "1.5", "kg", "Other spices / packets / pantry"),
    ("Maggi Rich Gravy Mix", "", "2", "kg", "Other spices / packets / pantry"),
    ("Maggi Instant Rich Gravy Mix (GF)", "", "3.5", "kg", "Other spices / packets / pantry"),
    ("Rosemary Leaves", "Hoyts", "100", "g", "Other spices / packets / pantry"),
    ("Bay Leaves", "Hoyts", "15", "g", "Other spices / packets / pantry"),
    ("Smoky Paprika", "Trump", "500", "g", "Other spices / packets / pantry"),
    ("Ground Cumin", "", "2", "kg", "Other spices / packets / pantry"),
    ("Sweet Paprika", "", "1", "kg", "Other spices / packets / pantry"),
    ("Traditional Curry Powder", "Keen's", "360", "g", "Other spices / packets / pantry"),
    ("Coriander Leaves", "MasterFoods", "5", "g", "Other spices / packets / pantry"),
    ("Nutmeg (Ground)", "MasterFoods", "30", "g", "Other spices / packets / pantry"),
    ("Ginger (Ground)", "Woolworths", "25", "g", "Other spices / packets / pantry"),
    ("Nutmeg (Ground)", "Woolworths", "30", "g", "Other spices / packets / pantry"),
    ("Queen Unicorn Confetti", "", "110", "g", "Other spices / packets / pantry"),
    ("Garlic Herb Salt Blend", "MasterFoods", "31", "g", "Other spices / packets / pantry"),
    ("Keen's Mustard Powder", "", "3", "× 50 g", "Other spices / packets / pantry"),
    ("Cumin (Ground)", "Woolworths", "30", "g", "Other spices / packets / pantry"),
    ("Cloves (Ground)", "Woolworths", "30", "g", "Other spices / packets / pantry"),
    ("French Onion Soup", "Woolworths Essentials", "40", "g", "Other spices / packets / pantry"),
    ("Onion Powder", "", "38", "g", "Other spices / packets / pantry"),
    ("Ground Coriander", "MasterFoods", "30", "g", "Other spices / packets / pantry"),
    ("Vanilla Bean Pods", "Queen", "5", "pods left", "Other spices / packets / pantry"),
    ("Gourmet Veggie Stock Powder", "Vegeta", "100", "g", "Other spices / packets / pantry"),
    ("Whole Black Peppercorns", "McKenzie's", "200", "g", "Other spices / packets / pantry"),
    ("Natural Sea Salt", "Saxa", "15", "g", "Other spices / packets / pantry"),
    ("Black Peppercorn Grinder", "Woolworths", "50", "g", "Other spices / packets / pantry"),
    ("Agar Agar", "Lotus", "75", "g", "Other spices / packets / pantry"),
    ("Cocoa Powder", "Nestlé", "~95", "g", "Other spices / packets / pantry"),
    ("Plaistowe Cocoa Powder", "Nestlé", "180", "g", "Other spices / packets / pantry"),
    ("Classic Freeze Dried Coffee", "Woolworths", "50", "g", "Other spices / packets / pantry"),
    ("Freeze Dried Coffee (Combined)", "Woolworths", "100", "g total", "Other spices / packets / pantry"),
    ("Pistachio Spread", "Pisti", "1.5", "× 500 g jars", "Other spices / packets / pantry"),
    ("Hazelnut Cream Spread", "Pisti", "300", "g", "Other spices / packets / pantry"),
    ("Pistachio Spread", "Pisti", "2", "× 180 g", "Other spices / packets / pantry"),
    ("Pistachio Spread", "", "2", "× 600 g", "Other spices / packets / pantry"),
    ("Nutella", "", "1", "kg", "Other spices / packets / pantry"),
    ("Pure Honey", "Super Bee", "10", "kg", "Other spices / packets / pantry"),
    ("Apricot & Macadamia Specialty Crackers", "OB Finest", "2", "packs", "Crackers and snacks"),
    ("GF Date & Almond Crackers", "OB Finest", "2", "packs", "Crackers and snacks"),
    ("Fig & Cranberry Crackers", "OB Finest", "2", "packs", "Crackers and snacks"),
    ("Fig & Almond Crackers", "OB Finest", "2", "packs", "Crackers and snacks"),
    ("GF Fig & Pistachio Crackers", "OB Finest", "1", "pack", "Crackers and snacks"),
    ("Original Wafer Crackers", "OB Finest", "1.5", "packs", "Crackers and snacks"),
    ("Dried Apricots", "", "500", "g", "Crackers and snacks"),
    ("Chilli Lime Soy Crisps", "BlueWorks", "2", "× 400 g", "Crackers and snacks"),
    ("Original Crisps", "Smith's", "170", "g", "Crackers and snacks"),
    ("Sea Salt & Sesame Artisan Crackers", "Valley Produce Co.", "130", "g", "Crackers and snacks"),
    ("Cracked Black Pepper Water Crackers", "Captain's Table", "125", "g", "Crackers and snacks"),
    ("Lindt Easter Hen Milk Chocolate Eggs", "", "1", "pc", "Chocolate / sweets"),
    ("Cadbury Dairy Milk Chocolate", "", "8", "× 100 g", "Chocolate / sweets"),
    ("Vegemite", "", "100", "g", "Chocolate / sweets"),
    ("Bickford's Pomegranate Juice", "", "2", "× 1 L", "Chocolate / sweets"),
]


def main():
    seen_slugs = {}
    items = []
    for name, brand, dq, du, cat in RAW:
        z = zone_for(cat)
        p = prefix_for_zone(z)
        base = slug(name)
        n = seen_slugs.get((p, base), 0)
        seen_slugs[(p, base)] = n + 1
        item_id = f"{p}-{base}" + (f"-{n}" if n else "")
        items.append(
            {
                "id": item_id,
                "name": name,
                "zone": z,
                "category": cat,
                "brand": brand,
                "defaultQty": dq,
                "defaultUom": du,
            }
        )

    header = """/**
 * Riviera built-in stocktake catalog (snapshot). Loaded by riviera.html stocktake modal.
 * Generated by scripts/generate_riviera_stocktake_data.py — do not hand-edit; regenerate instead.
 */
(function () {
  'use strict';
  window.RIVIERA_STOCKTAKE_CATALOG = """
    footer = """;
})();
"""
    js = header + json.dumps(items, ensure_ascii=False, indent=2) + footer
    OUT.write_text(js, encoding="utf-8")
    print(f"Wrote {len(items)} items to {OUT}")


if __name__ == "__main__":
    main()
