#!/usr/bin/env node
/**
 * Normalise + merge Riviera built-in ingredients (SSOT) and emit order-override remap v2.
 * Usage: node scripts/normalize_merge_riviera_builtins.mjs [--dry-run]
 */
import fs from 'fs';
import path from 'path';
import vm from 'vm';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

function runInThisGlobal(relPath) {
  const code = fs.readFileSync(path.join(root, relPath), 'utf8');
  vm.runInThisContext(code, { filename: relPath });
}

const dryRun = process.argv.includes('--dry-run');

runInThisGlobal('assets/riviera-canonical-ingredient.js');
runInThisGlobal('assets/recipe-metric-normalize.js');
runInThisGlobal('assets/riviera-ingredient-merge.js');

const Merge = globalThis.KuschiRivieraIngredientMerge;
if (!Merge) {
  console.error('Failed to load merge/metric globals');
  process.exit(1);
}

const builtinsPath = path.join(root, 'riviera_data', 'builtins.json');
const raw = JSON.parse(fs.readFileSync(builtinsPath, 'utf8'));
if (!Array.isArray(raw)) {
  console.error('builtins.json must be a JSON array');
  process.exit(1);
}

const imperialQty = /\b(cup|cups|tbsp|tablespoon|tablespoons|tsp|teaspoon|teaspoons|oz\.?|lb|lbs|pound|ounces?)\b/i;

let recipesTouched = 0;
let rowsRemoved = 0;
let groupsMerged = 0;
const maps = {};
const imperialHits = [];

for (let i = 0; i < raw.length; i++) {
  const recipe = raw[i];
  if (!recipe || typeof recipe !== 'object') continue;
  const id = recipe.id;
  const before = recipe.ingredients || [];
  const oldLen = before.length;

  const res = Merge.mergeRivieraRecipeIngredients(recipe);
  if (!res.changed) continue;

  recipesTouched++;
  rowsRemoved += res.stats.rowsRemoved || 0;
  groupsMerged += res.stats.groupsMerged || 0;

  for (let j = 0; j < (res.recipe.ingredients || []).length; j++) {
    const q = String(res.recipe.ingredients[j].qty || '');
    if (imperialQty.test(q)) imperialHits.push({ id, index: j, qty: q, item: res.recipe.ingredients[j].item });
  }

  const oldToNew = res.oldToNewIndex || {};
  let nonIdentity = false;
  const fullMap = {};
  for (let oi = 0; oi < oldLen; oi++) {
    const ni = oldToNew[oi] !== undefined ? oldToNew[oi] : oi;
    fullMap[String(oi)] = ni;
    if (ni !== oi) nonIdentity = true;
  }
  if (nonIdentity || (res.ingredients || []).length !== oldLen) {
    maps[id] = fullMap;
  }

  if (!dryRun) {
    raw[i] = res.recipe;
  }
}

console.log(
  JSON.stringify(
    {
      recipesTotal: raw.length,
      recipesTouched,
      groupsMerged,
      rowsRemoved,
      remapRecipeCount: Object.keys(maps).length,
      dryRun,
    },
    null,
    2
  )
);

if (imperialHits.length) {
  console.warn('Ingredient qty fields still matching imperial tokens (review):', imperialHits.length);
  console.warn(imperialHits.slice(0, 20));
}

if (!dryRun) {
  if (recipesTouched === 0) {
    console.log('No changes; leaving builtins.json and remap artefacts unchanged.');
  } else {
    fs.writeFileSync(builtinsPath, JSON.stringify(raw, null, 2) + '\n', 'utf8');

    const remapPayload = { version: 2, maps };
    fs.writeFileSync(path.join(root, 'riviera_data', 'order_override_remap_v2.json'), JSON.stringify(remapPayload, null, 2) + '\n', 'utf8');

    const jsOut = `/* Generated by scripts/normalize_merge_riviera_builtins.mjs — do not hand-edit */\n(function (g) {\n  g.KuschiRivieraOrderOverrideRemapV2 = ${JSON.stringify(remapPayload)};\n})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);\n`;
    fs.writeFileSync(path.join(root, 'assets', 'riviera-order-override-remap-v2.js'), jsOut, 'utf8');
    console.log('Wrote riviera_data/builtins.json, riviera_data/order_override_remap_v2.json, assets/riviera-order-override-remap-v2.js');
  }
}
