# -*- coding: utf-8 -*-
"""House-authored Riviera built-in payloads for expansion waves (see docs/riviera_recipe_expansion_manifest.json)."""

WAVE_A = [
    {
        "id": "bruschetta-rare-roast-beef",
        "name": "Bruschetta of Rare Roast Beef",
        "subtitle": "Charred Sourdough · Horseradish Cream · Pickled Shallot",
        "type": "Canape",
        "course": "Canape",
        "protein": ["beef"],
        "diet": [],
        "method": "Assemble",
        "yield": "40 pieces",
        "label": "Beef Bruschetta",
        "elements": ["Crostini", "Rare Beef", "Horseradish Cream", "Pickled Shallot"],
        "ingredients": [
            {"qty": "1 loaf", "item": "Sourdough Batard", "prep": "slice 1.5cm, char both sides"},
            {"qty": "800 g", "item": "Beef Striploin", "prep": "sear rare, slice paper-thin across grain"},
            {"qty": "300 ml", "item": "Thickened Cream"},
            {"qty": "80 g", "item": "Horseradish — Prepared", "prep": "drained"},
            {"qty": "15 ml", "item": "Red Wine Vinegar"},
            {"qty": "4", "item": "Shallots", "prep": "fine rings, quick pickle 20 min in vinegar + pinch salt"},
            {"qty": "40 g", "item": "Chives", "prep": "snipped"},
            {"qty": "20 ml", "item": "Olive Oil", "prep": "brush for bread"},
            {"qty": "to taste", "item": "Salt Flakes & Cracked Pepper"},
        ],
        "method_steps": [
            "CROSTINI: Slice sourdough, brush lightly with oil, char on grill or hot pan until marked. Cool on rack.",
            "HORSERADISH CREAM: Whisk cream to soft peaks, fold in horseradish and vinegar. Season. Hold chilled in PC.",
            "BEEF: Season striploin, sear hard on all faces, rest 8 minutes, slice as thin as possible across grain. Hold lightly covered — service same day.",
            "PICKLED SHALLOT: Slice shallots, cover with vinegar and a pinch of salt; drain before service.",
            "ASSEMBLY: Spread thin horseradish cream on crostini, drape beef, top with shallot rings and chives.",
        ],
        "service": [
            "Room-temp canapé: plate on slate or board; finish with flaky salt at pass.",
            "Hold assembled no more than 20 minutes before pass to keep bread crisp.",
        ],
        "note": "Event canapé spec — scale beef 20g raw weight per piece equivalent.",
    },
    {
        "id": "spanner-crab-cannoli",
        "name": "Spanner Crab Cannoli",
        "subtitle": "Citrus · Dill · Crisp Shell",
        "type": "Canape",
        "course": "Canape",
        "protein": ["seafood"],
        "diet": [],
        "method": "Fry + Pipe",
        "yield": "40 small cannoli",
        "label": "Crab Cannoli",
        "elements": ["Shell", "Spanner Crab Filling", "Microherbs"],
        "ingredients": [
            {"qty": "600 g", "item": "Spanner Crab Meat", "prep": "picked, drained"},
            {"qty": "200 g", "item": "Cream Cheese", "prep": "softened"},
            {"qty": "80 ml", "item": "Lemon Juice"},
            {"qty": "1 bunch", "item": "Dill", "prep": "fine chop"},
            {"qty": "2 tsp", "item": "Tabasco", "prep": "optional heat"},
            {"qty": "40", "item": "Mini Cannoli Shells", "prep": "GF if required"},
            {"qty": "1 punnet", "item": "Microherbs — Garnish"},
            {"qty": "to taste", "item": "Salt & White Pepper"},
        ],
        "method_steps": [
            "FILLING: Fold crab with cream cheese, lemon juice, dill, tabasco. Season. Pipe into piping bag, hold chilled 2 hours max before fill.",
            "SHELLS: Fry shells if raw pastry type per supplier spec; cool completely before filling.",
            "PIPE: Fill both ends of each shell just before service for maximum crunch.",
        ],
        "service": [
            "Pass on trays with microherb garnish; lemon cheek on side of tray.",
        ],
        "note": "If shells soften, under-fill and refresh garnish only.",
    },
    {
        "id": "prawn-brioche-slider",
        "name": "Prawn Brioche Slider",
        "subtitle": "Cocktail Sauce · Lettuce · Potato Crisp",
        "type": "Canape",
        "course": "Canape",
        "protein": ["seafood"],
        "diet": [],
        "method": "Grill + Assemble",
        "yield": "40 sliders",
        "label": "Prawn Slider",
        "elements": ["Tiger Prawn", "Brioche Bun", "Sauce", "Lettuce", "Crisp"],
        "ingredients": [
            {"qty": "2 kg", "item": "Tiger Prawns", "prep": "peeled, tail-off, butterflied"},
            {"qty": "40", "item": "Brioche Slider Buns", "prep": "split"},
            {"qty": "400 ml", "item": "Kewpie Mayo"},
            {"qty": "80 ml", "item": "Tomato Ketchup"},
            {"qty": "30 ml", "item": "Worcestershire Sauce"},
            {"qty": "15 ml", "item": "Lemon Juice"},
            {"qty": "1 head", "item": "Baby Cos", "prep": "small leaves"},
            {"qty": "200 g", "item": "Potato Crisps", "prep": "crushed"},
            {"qty": "40 ml", "item": "Olive Oil", "prep": "brush prawns"},
            {"qty": "30 g", "item": "Cajun or Lemon Pepper Seasoning"},
        ],
        "method_steps": [
            "SAUCE: Whisk mayo, ketchup, Worcestershire, lemon — cocktail sauce. Hold chilled.",
            "PRAWNS: Toss with oil and seasoning, grill or hot pan 90 seconds per side until just opaque. Chill quickly if holding cold.",
            "BUN: Warm brioche 170°C 4 minutes. Cool slightly before build.",
            "BUILD: Base bun, sauce, cos, prawn, pinch crushed crisps, lid skewer.",
        ],
        "service": [
            "Hot pass: grill prawns to order if possible; otherwise warm prawns gently in oven with steam cover off.",
        ],
        "note": "Sister build to reef fish slider — prawn variant for catering packages.",
    },
    {
        "id": "chicken-bacon-brioche-slider",
        "name": "Smoked Chicken & Bacon Brioche Slider",
        "subtitle": "Aioli · Rocket",
        "type": "Canape",
        "course": "Canape",
        "protein": ["chicken", "pork"],
        "diet": [],
        "method": "Oven + Assemble",
        "yield": "40 sliders",
        "label": "Chicken Bacon Slider",
        "elements": ["Smoked Chicken", "Crispy Bacon", "Brioche", "Aioli", "Rocket"],
        "ingredients": [
            {"qty": "2.5 kg", "item": "Chicken Thigh", "prep": "smoke or roast with smoke dust"},
            {"qty": "500 g", "item": "Streaky Bacon", "prep": "bake until crisp, crumble"},
            {"qty": "40", "item": "Brioche Slider Buns"},
            {"qty": "300 g", "item": "Kewpie Mayo"},
            {"qty": "2 cloves", "item": "Garlic", "prep": "grated"},
            {"qty": "200 g", "item": "Rocket"},
            {"qty": "to taste", "item": "Salt & Pepper"},
        ],
        "method_steps": [
            "CHICKEN: Roast thigh to 75°C internal, cool, shred coarse. Season.",
            "AIOLI: Mix mayo, garlic, salt — hold chilled.",
            "ASSEMBLY: Toast buns lightly. Base aioli, rocket, chicken, bacon crumb, lid.",
        ],
        "service": [
            "Serve warm; bacon added at last second for crunch.",
        ],
        "note": None,
    },
    {
        "id": "vintage-beef-brioche-slider",
        "name": "Vintage Beef Brioche Slider",
        "subtitle": "Aged Cheddar · Tomato Relish · Rocket",
        "type": "Canape",
        "course": "Canape",
        "protein": ["beef", "dairy"],
        "diet": [],
        "method": "Grill + Assemble",
        "yield": "40 sliders",
        "label": "Beef Slider",
        "elements": ["Beef Patty", "Cheddar", "Brioche", "Relish", "Rocket"],
        "ingredients": [
            {"qty": "2 kg", "item": "Beef Mince — Premium", "prep": "40 × 50g patties, seasoned"},
            {"qty": "400 g", "item": "Vintage Cheddar", "prep": "slices"},
            {"qty": "40", "item": "Brioche Slider Buns"},
            {"qty": "400 g", "item": "Tomato Relish", "prep": "house or quality bought"},
            {"qty": "200 g", "item": "Rocket"},
        ],
        "method_steps": [
            "PATTY: Flatten 50g balls, grill or pan to medium, rest on tray with cheddar on top to melt slightly.",
            "BUN: Warm buns.",
            "BUILD: Relish on base, rocket, patty with cheese, lid.",
        ],
        "service": [
            "Hot hold max 15 minutes under cloche for texture.",
        ],
        "note": None,
    },
    {
        "id": "mini-beefburger-canape",
        "name": "Mini Beefburger Canapé",
        "subtitle": "Aged Cheddar · Herbed Aioli · Tomato Relish · Rocket",
        "type": "Canape",
        "course": "Canape",
        "protein": ["beef", "dairy"],
        "diet": [],
        "method": "Grill + Assemble",
        "yield": "50 mini burgers",
        "label": "Mini Burger",
        "elements": ["Mini Patty", "Bun", "Aioli", "Relish", "Rocket"],
        "ingredients": [
            {"qty": "2.5 kg", "item": "Beef Mince"},
            {"qty": "50", "item": "Mini Burger Buns", "prep": "or slider buns halved"},
            {"qty": "300 g", "item": "Aged Cheddar", "prep": "small squares"},
            {"qty": "400 g", "item": "Kewpie Mayo"},
            {"qty": "1 bunch", "item": "Mixed Soft Herbs", "prep": "fine chop into mayo"},
            {"qty": "300 g", "item": "Tomato Relish"},
            {"qty": "150 g", "item": "Rocket"},
        ],
        "method_steps": [
            "HERBED AIOLI: Fold herbs through mayo, season.",
            "PATTY: 25g balls, smash-cook or small ring mould to 6cm rounds.",
            "ASSEMBLY: Toasted bun, aioli, relish, rocket, patty, cheese, lid pick.",
        ],
        "service": [
            "Bamboo pick mandatory for cocktail service.",
        ],
        "note": None,
    },
    {
        "id": "beef-polpette-canape",
        "name": "Beef Polpette",
        "subtitle": "Glaze or Sugo · Parmesan",
        "type": "Canape",
        "course": "Canape",
        "protein": ["beef", "dairy"],
        "diet": ["Gluten-Free"],
        "method": "Oven Bake",
        "yield": "80 pieces @ 25g",
        "label": "Polpette",
        "elements": ["Polpette", "Glaze", "Parmesan"],
        "ingredients": [
            {"qty": "2 kg", "item": "Beef Mince"},
            {"qty": "200 g", "item": "Parmesan", "prep": "grated"},
            {"qty": "2", "item": "Brown Onions", "prep": "fine dice, sweated"},
            {"qty": "4 cloves", "item": "Garlic", "prep": "crushed"},
            {"qty": "100 g", "item": "GF Breadcrumbs"},
            {"qty": "2", "item": "Eggs"},
            {"qty": "20 g", "item": "Salt"},
            {"qty": "10 g", "item": "Black Pepper"},
            {"qty": "500 ml", "item": "Tomato Passata", "prep": "reduced glaze or use romesco sugo line"},
        ],
        "method_steps": [
            "Mix mince, parmesan, cooled onion, garlic, crumbs, eggs, seasoning. Roll 25g balls.",
            "Bake 180°C 12 minutes until coloured; glaze with reduced passata; finish parmesan.",
        ],
        "service": [
            "Toothpick or bamboo boat; extra glaze in squeeze bottle at pass.",
        ],
        "note": "Smaller format than slow-cooked veal meatballs; can share romesco line if desired.",
    },
    {
        "id": "lamb-shoulder-provencale-composed",
        "name": "Slow Cooked Lamb Shoulder Provençale",
        "subtitle": "Moroccan Couscous · Harissa Yoghurt",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["lamb", "dairy"],
        "diet": [],
        "method": "Slow Bake + Simmer",
        "yield": "30 mains",
        "label": "Lamb Shoulder Plate",
        "elements": ["Lamb Shoulder", "Moroccan Couscous", "Harissa Yoghurt"],
        "ingredients": [
            {"qty": "6 kg", "item": "Lamb Shoulder — Bone In", "prep": "trim excess fat"},
            {"qty": "100 ml", "item": "Olive Oil"},
            {"qty": "4 tbsp", "item": "Rosemary & Thyme", "prep": "chopped"},
            {"qty": "200 g", "item": "Tomato Paste"},
            {"qty": "500 ml", "item": "White Wine"},
            {"qty": "2 L", "item": "Chicken Stock"},
            {"qty": "1.2 kg", "item": "Couscous — Medium"},
            {"qty": "2 L", "item": "Stock — Hot", "prep": "chicken or veg"},
            {"qty": "200 g", "item": "Butter", "prep": "diced"},
            {"qty": "150 g", "item": "Sultanas", "prep": "plumped hot stock"},
            {"qty": "80 g", "item": "Toasted Almonds", "prep": "sliced"},
            {"qty": "2 tbsp", "item": "Ras el Hanout"},
            {"qty": "1 kg", "item": "Greek Yoghurt"},
            {"qty": "80 g", "item": "Harissa Paste", "prep": "adjust heat"},
            {"qty": "2", "item": "Lemons", "prep": "zest + juice"},
            {"qty": "20 g", "item": "Salt"},
        ],
        "method_steps": [
            "HARISSA YOGHURT: Whisk yoghurt, harissa, lemon zest/juice, salt to taste. Hold chilled 24h max in PC.",
            "COUSCOUS: Bloom couscous with hot stock, butter, sultanas, almonds, ras el hanout — fluff with fork. Hold hot box.",
            "LAMB: Rub shoulder with oil, herbs, salt. Sear all sides. Add tomato paste, wine, reduce slightly, add stock to half-cover. Cover foil, 150°C 5–6 hours until pulling.",
            "PICK lamb, reduce jus on stove, adjust seasoning. Shred or slice for service.",
            "PLATE: Base couscous, lamb, drizzle jus, quenelle yoghurt, extra harissa dots optional.",
        ],
        "service": [
            "Family or individual: keep yoghurt cold until last moment.",
        ],
        "note": "Composite card — all three components specified in one modal per house policy.",
    },
    {
        "id": "beef-bourguignon",
        "name": "Beef Bourguignon",
        "subtitle": "Red Wine · Bacon · Mushroom · Carrot",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["beef", "pork"],
        "diet": ["Gluten-Free"],
        "method": "Slow Simmer",
        "yield": "4 kg finished",
        "label": "Beef Bourguignon",
        "elements": ["Beef Cheek or Chuck", "Red Wine Jus", "Garnish Vegetables"],
        "ingredients": [
            {"qty": "4 kg", "item": "Beef Cheek or Chuck", "prep": "large dice"},
            {"qty": "500 g", "item": "Speck or Bacon", "prep": "lardons"},
            {"qty": "1 kg", "item": "Button Mushrooms", "prep": "halved"},
            {"qty": "500 g", "item": "Carrot", "prep": "chunk"},
            {"qty": "500 g", "item": "Brown Onion", "prep": "chunk"},
            {"qty": "1 bottle", "item": "Red Wine", "prep": "bold dry"},
            {"qty": "2 L", "item": "Beef Stock"},
            {"qty": "200 g", "item": "Tomato Paste"},
            {"qty": "4", "item": "Bay Leaves"},
            {"qty": "4 sprigs", "item": "Thyme"},
            {"qty": "40 g", "item": "Cornflour", "prep": "slurry to finish"},
        ],
        "method_steps": [
            "Sear beef in batches, reserve. Render bacon, add mushrooms colour, add onion carrot.",
            "Stir tomato paste, add wine, reduce by third. Add stock, herbs, beef back. Simmer covered 3h low until tender.",
            "Reduce sauce, thicken lightly with cornflour slurry if needed. Adjust salt.",
        ],
        "service": [
            "Hold hot in bain; parsley garnish.",
        ],
        "note": None,
    },
    {
        "id": "creamy-lemon-caper-chicken",
        "name": "Creamy Lemon Caper Chicken",
        "subtitle": "Thyme · White Wine · Cream",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["chicken", "dairy"],
        "diet": ["Gluten-Free"],
        "method": "Pan + Simmer",
        "yield": "30 portions",
        "label": "Lemon Caper Chicken",
        "elements": ["Chicken Supreme", "Sauce", "Herbs"],
        "ingredients": [
            {"qty": "6 kg", "item": "Chicken Breast Supreme", "prep": "skin-on optional"},
            {"qty": "200 g", "item": "Butter"},
            {"qty": "200 ml", "item": "White Wine"},
            {"qty": "500 ml", "item": "Thickened Cream"},
            {"qty": "100 ml", "item": "Lemon Juice"},
            {"qty": "2", "item": "Lemons", "prep": "zest"},
            {"qty": "150 g", "item": "Baby Capers", "prep": "drained"},
            {"qty": "1 bunch", "item": "Thyme"},
            {"qty": "to taste", "item": "Salt & White Pepper"},
        ],
        "method_steps": [
            "Pan-sear chicken skin-side until golden, flip, finish to 74°C internal. Rest half, slice for buffet if needed.",
            "Sauce: deglaze pan with wine, reduce, add cream, lemon zest/juice, capers, thyme. Simmer to nappe.",
            "Return chicken to sauce or nap over slices.",
        ],
        "service": [
            "Sauce split if holding — refresh with splash cream at pass.",
        ],
        "note": "Shares flavour lane with lemon dill aioli for cold applications if repurposed.",
    },
    {
        "id": "natural-oysters-champagne-mignonette",
        "name": "Natural Oysters with Champagne Mignonette",
        "subtitle": "Shucked · Chilled · Mignonette",
        "type": "Canape",
        "course": "Canape",
        "protein": ["seafood"],
        "diet": ["Gluten-Free", "Dairy-Free"],
        "method": "Raw + Mix",
        "yield": "Scalable",
        "label": "Natural Oysters",
        "elements": ["Oysters", "Champagne Mignonette", "Lemon"],
        "ingredients": [
            {"qty": "", "item": "Oysters", "prep": "shucked to order or HACCP window per SOP"},
            {"qty": "200 ml", "item": "Champagne or Sparkling Wine"},
            {"qty": "60 ml", "item": "Champagne Vinegar or White Wine Vinegar"},
            {"qty": "2 shallots", "item": "Shallots", "prep": "brunoise"},
            {"qty": "1 tsp", "item": "Cracked Pepper"},
            {"qty": "pinch", "item": "Caster Sugar"},
            {"qty": "6", "item": "Lemons", "prep": "cheeks for service"},
        ],
        "method_steps": [
            "MIGNONETTE: Combine champagne, vinegar, shallot, pepper, sugar. Rest 30 minutes. Hold chilled.",
            "Oysters: shuck into deep half-shell, check for shell, store on crushed ice with flat side down.",
        ],
        "service": [
            "Serve on ice with spoon of mignonette beside, not on oyster until guest chooses.",
        ],
        "note": "Separate from Kilpatrick — cold natural line.",
    },
    {
        "id": "greek-spiced-roast-lamb",
        "name": "Greek Spiced Roast Lamb Leg",
        "subtitle": "Oregano · Lemon · Garlic · Olive Oil",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["lamb"],
        "diet": ["Gluten-Free", "Dairy-Free"],
        "method": "Oven Roast",
        "yield": "1 leg ~18 portions",
        "label": "Greek Lamb Leg",
        "elements": ["Lamb Leg", "Greek Marinade", "Pan Juices"],
        "ingredients": [
            {"qty": "1", "item": "Lamb Leg — Bone In", "prep": "3–4 kg"},
            {"qty": "200 ml", "item": "Olive Oil"},
            {"qty": "6 cloves", "item": "Garlic", "prep": "sliced"},
            {"qty": "4", "item": "Lemons", "prep": "juice + zest"},
            {"qty": "3 tbsp", "item": "Dried Oregano"},
            {"qty": "2 tsp", "item": "Ground Cumin"},
            {"qty": "2 tsp", "item": "Sweet Paprika"},
            {"qty": "40 g", "item": "Salt"},
            {"qty": "20 g", "item": "Black Pepper"},
        ],
        "method_steps": [
            "Score fat cap, rub marinade all over, marinate 24h chilled.",
            "Roast 160°C to internal 62°C rest target ~58°C after rest for pink — adjust to house policy.",
            "Rest 20 minutes, carve, finish with pan juices.",
        ],
        "service": [
            "Carvery or plated; tzatziki line optional side.",
        ],
        "note": "Optional brine: see Lamb Citrus Herb Brine card for large-batch prep.",
    },
    {
        "id": "creamy-potato-gratin",
        "name": "Creamy Potato Gratin",
        "subtitle": "Cream · Garlic · Golden Cheese Crust",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["dairy"],
        "diet": ["Vegetarian", "Gluten-Free"],
        "method": "Bake",
        "yield": "Full gastronorm",
        "label": "Potato Gratin",
        "elements": ["Potato Layers", "Cream", "Cheese"],
        "ingredients": [
            {"qty": "5 kg", "item": "Desiree Potato", "prep": "mandolin 3mm"},
            {"qty": "2 L", "item": "Thickened Cream"},
            {"qty": "500 ml", "item": "Milk"},
            {"qty": "8 cloves", "item": "Garlic", "prep": "sliced paper thin"},
            {"qty": "300 g", "item": "Gruyère or Tasty", "prep": "grated"},
            {"qty": "30 g", "item": "Salt"},
            {"qty": "5 g", "item": "White Pepper", "prep": "ground"},
        ],
        "method_steps": [
            "Rub deep tray with garlic, layer potato, season every layer, finish with cream+milk just covering top potato.",
            "Bake 160°C covered 60m, uncover, cheese, bake 30m until blistered.",
            "Rest 20m before portion — holds hot box 2h.",
        ],
        "service": [
            "Square portions with offset spatula.",
        ],
        "note": None,
    },
    {
        "id": "garlic-herb-chat-potatoes-feta",
        "name": "Garlic & Herb Chat Potatoes with Feta Cream",
        "subtitle": "Roast · Whipped Feta",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["dairy"],
        "diet": ["Vegetarian", "Gluten-Free"],
        "method": "Roast + Blend",
        "yield": "30 sides",
        "label": "Chat Potatoes",
        "elements": ["Roast Chats", "Feta Cream", "Herbs"],
        "ingredients": [
            {"qty": "4 kg", "item": "Baby Chat Potatoes", "prep": "halved if large"},
            {"qty": "150 ml", "item": "Olive Oil"},
            {"qty": "50 g", "item": "Garlic", "prep": "crushed"},
            {"qty": "1 bunch", "item": "Rosemary & Thyme", "prep": "picked"},
            {"qty": "400 g", "item": "Danish Feta", "prep": "whipped smooth with 100ml cream"},
            {"qty": "100 ml", "item": "Thickened Cream"},
            {"qty": "to taste", "item": "Salt Flakes"},
        ],
        "method_steps": [
            "Toss chats with oil, garlic, herbs, salt. Roast 200°C until golden and crisp outside.",
            "Feta cream: blend feta with cream until pipeable, hold chilled.",
        ],
        "service": [
            "Serve chats hot, quenelle feta cream on side or drizzle.",
        ],
        "note": None,
    },
    {
        "id": "broccoli-cauliflower-gratin",
        "name": "Broccoli & Cauliflower Gratin",
        "subtitle": "Béchamel · Cheese Crust",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["dairy"],
        "diet": ["Vegetarian", "Gluten-Free"],
        "method": "Bake",
        "yield": "Gastronorm",
        "label": "Veg Gratin",
        "elements": ["Florets", "Béchamel", "Cheese"],
        "ingredients": [
            {"qty": "2 kg", "item": "Broccoli", "prep": "florets"},
            {"qty": "2 kg", "item": "Cauliflower", "prep": "florets"},
            {"qty": "100 g", "item": "Butter"},
            {"qty": "100 g", "item": "Cornflour", "prep": "for GF roux"},
            {"qty": "2 L", "item": "Milk", "prep": "hot"},
            {"qty": "400 g", "item": "Tasty Cheese", "prep": "grated"},
            {"qty": "1 pinch", "item": "Nutmeg"},
            {"qty": "to taste", "item": "Salt & White Pepper"},
        ],
        "method_steps": [
            "Blanch florets 3 min, drain well.",
            "Roux with butter and cornflour, cook out, whisk milk to thick béchamel, nutmeg, half cheese.",
            "Fold veg, top with remaining cheese, bake 190°C 25m until golden.",
        ],
        "service": [
            "Rest 10m before scoop — sauce sets slightly.",
        ],
        "note": None,
    },
    {
        "id": "prosciutto-chicken-lemon-caper",
        "name": "Prosciutto Wrapped Chicken Breast",
        "subtitle": "Potato · Greens · Lemon Caper Cream",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["chicken", "pork"],
        "diet": ["Gluten-Free"],
        "method": "Oven Bake",
        "yield": "30 portions",
        "label": "Prosciutto Chicken",
        "elements": ["Chicken", "Prosciutto", "Lemon Caper Cream", "Potato", "Greens"],
        "ingredients": [
            {"qty": "6 kg", "item": "Chicken Breast", "prep": "skinless"},
            {"qty": "600 g", "item": "Prosciutto", "prep": "thin slices"},
            {"qty": "500 ml", "item": "Thickened Cream"},
            {"qty": "100 ml", "item": "Lemon Juice"},
            {"qty": "100 g", "item": "Baby Capers"},
            {"qty": "3 kg", "item": "Chat Potatoes", "prep": "roasted with oil salt"},
            {"qty": "2 bags", "item": "Mixed Leaf", "prep": "dressed lemon oil"},
            {"qty": "to taste", "item": "Salt & Pepper"},
        ],
        "method_steps": [
            "Wrap each breast in prosciutto, sear colour, bake 180°C to 74°C internal.",
            "Sauce: reduce cream with lemon and capers until coats spoon.",
            "Potatoes: roast separately until crisp outside.",
        ],
        "service": [
            "Slice chicken on bias, stack potato, greens, sauce nap.",
        ],
        "note": "Composite elements in one card for plated package.",
    },
    {
        "id": "fillet-beef-tempranillo",
        "name": "Fillet of Beef with Tempranillo Reduction",
        "subtitle": "Potato · Greens",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["beef"],
        "diet": ["Gluten-Free"],
        "method": "Pan + Simmer",
        "yield": "30 portions",
        "label": "Beef Fillet",
        "elements": ["Beef Fillet", "Tempranillo Reduction", "Potato", "Greens"],
        "ingredients": [
            {"qty": "4 kg", "item": "Beef Fillet", "prep": "portion 130g"},
            {"qty": "750 ml", "item": "Tempranillo Wine"},
            {"qty": "500 ml", "item": "Beef Stock"},
            {"qty": "50 g", "item": "Shallots", "prep": "diced"},
            {"qty": "30 g", "item": "Butter", "prep": "mount sauce"},
            {"qty": "3 kg", "item": "Potato", "prep": "roast or gratin per event spec"},
            {"qty": "2 bags", "item": "Mixed Greens"},
        ],
        "method_steps": [
            "Sear fillet portions, oven finish to medium-rare policy, rest.",
            "Reduction: shallot in pan, add wine reduce 80%, add stock reduce to glaze, mount butter, strain.",
        ],
        "service": [
            "Slice fillet fan, sauce stripe, veg alongside.",
        ],
        "note": None,
    },
    {
        "id": "stuffed-mushroom-romesco",
        "name": "Stuffed Mushroom with Romesco & Lemon Aioli",
        "subtitle": "Greens",
        "type": "Canape",
        "course": "Canape",
        "protein": [],
        "diet": ["Vegetarian", "Gluten-Free"],
        "method": "Bake",
        "yield": "60 pieces",
        "label": "Stuffed Mushroom",
        "elements": ["Portobello Cup", "Romesco", "Lemon Aioli", "Greens"],
        "ingredients": [
            {"qty": "60", "item": "Portobello Mushrooms", "prep": "small cups, stems reserved for duxelles"},
            {"qty": "1 kg", "item": "Romesco", "prep": "from batch"},
            {"qty": "300 g", "item": "Lemon Thyme Aioli", "prep": "from batch"},
            {"qty": "200 g", "item": "Panko — GF", "prep": "optional crunch"},
            {"qty": "200 g", "item": "Parmesan", "prep": "grated"},
            {"qty": "1 bag", "item": "Rocket"},
        ],
        "method_steps": [
            "Roast cups 10m to drive moisture, fill with romesco mixed with parmesan and panko, bake 12m until golden.",
            "Cool slightly, dot lemon aioli, pick of rocket.",
        ],
        "service": [
            "Warm pass; vegan cheese swap if required.",
        ],
        "note": "Uses house romesco and lemon thyme aioli batches.",
    },
    {
        "id": "roving-cannoli-tiramisu",
        "name": "Roving Cannoli & Tiramisu Service",
        "subtitle": "Strawberry Ricotta · Tiramisu · Lemon Cheesecake",
        "type": "Platter",
        "course": "Dessert",
        "protein": ["dairy"],
        "diet": ["Vegetarian"],
        "method": "Mix + Pipe",
        "yield": "100 roving serves",
        "label": "Roving Dessert",
        "elements": ["Cannoli Shell", "Fillings", "Garnish"],
        "ingredients": [
            {"qty": "100", "item": "Small Cannoli Shells"},
            {"qty": "1 kg", "item": "Ricotta", "prep": "strained"},
            {"qty": "300 g", "item": "Icing Sugar"},
            {"qty": "200 g", "item": "Freeze-dried Strawberry", "prep": "crushed"},
            {"qty": "500 g", "item": "Mascarpone"},
            {"qty": "200 ml", "item": "Espresso", "prep": "cold"},
            {"qty": "100 g", "item": "Cocoa Powder"},
            {"qty": "100 g", "item": "Toasted Almonds", "prep": "chopped"},
            {"qty": "200 g", "item": "White Chocolate", "prep": "shaved"},
            {"qty": "4", "item": "Lemons", "prep": "zest for lemon cheesecake variant"},
        ],
        "method_steps": [
            "STRAWBERRY RICOTTA: Beat ricotta with icing sugar, fold strawberry crumb. Pipe day-of.",
            "TIRAMISU FILLING: Fold mascarpone with espresso, cocoa, almonds to pipeable.",
            "LEMON CHEESECAKE: Blend ricotta, mascarpone, lemon zest, icing sugar until smooth.",
            "ROVING: staff with gloved hands fill shells to order or 5-minute batches max.",
        ],
        "service": [
            "Tray of mixed filled cannoli + napkins; alternate fillings on tray for visual.",
        ],
        "note": "Canape package add-on per Dec 2025 menu.",
    },
]

WAVE_B = [
    {
        "id": "platter-scones-chantilly-jam",
        "name": "House Baked Scones Platter",
        "subtitle": "Chantilly Cream · Jam",
        "type": "Platter",
        "course": "Platter",
        "protein": ["dairy"],
        "diet": ["Vegetarian"],
        "method": "Bake",
        "yield": "12 serves platter",
        "label": "Scone Platter",
        "elements": ["Scones", "Chantilly", "Jam"],
        "ingredients": [
            {"qty": "24", "item": "House Scones", "prep": "baked day-of"},
            {"qty": "500 ml", "item": "Thickened Cream", "prep": "whipped with vanilla and icing sugar — Chantilly"},
            {"qty": "400 g", "item": "Berry Jam", "prep": "decant to bowl"},
        ],
        "method_steps": [
            "Bake scones per bakery SOP, cool 10m on rack.",
            "Whip Chantilly to soft peaks, hold chilled.",
            "Platter: pile scones, bowls of jam and cream, cloth napkin under basket aesthetic.",
        ],
        "service": [
            "Self-serve wake style; refresh cream if warm room.",
        ],
        "note": "Funeral / wake platter line.",
    },
    {
        "id": "platter-sweet-slices-cakes",
        "name": "Sweet Slice & Cake Platter",
        "subtitle": "Chef Selection",
        "type": "Platter",
        "course": "Platter",
        "protein": ["dairy"],
        "diet": ["Vegetarian"],
        "method": "Assemble",
        "yield": "12 serves platter",
        "label": "Sweet Platter",
        "elements": ["Slices", "Petit Cakes"],
        "ingredients": [
            {"qty": "36 pieces", "item": "Assorted Slices", "prep": "chef selection"},
            {"qty": "12 pieces", "item": "Petit Cakes", "prep": "chef selection"},
        ],
        "method_steps": [
            "Cut uniform fingers, parchment between layers on platter.",
            "Label allergens on card at front of platter.",
        ],
        "service": [
            "Room temp 2h max; cover with dome when not in use.",
        ],
        "note": None,
    },
    {
        "id": "grazing-box-standard",
        "name": "Grazing Box",
        "subtitle": "Cheese · Deli · Fruit · Nuts · Crackers · Dips · Olives",
        "type": "Platter",
        "course": "Platter",
        "protein": ["pork", "dairy"],
        "diet": [],
        "method": "Assemble",
        "yield": "1 box ~12 picks",
        "label": "Grazing Box",
        "elements": ["Cheeses", "Meats", "Fruit", "Crackers", "Dips", "Olives"],
        "ingredients": [
            {"qty": "as needed", "item": "Cheese Selection", "prep": "3 types cubed"},
            {"qty": "as needed", "item": "Deli Meats", "prep": "rolled"},
            {"qty": "as needed", "item": "Seasonal Fruit", "prep": "grapes berries fig"},
            {"qty": "as needed", "item": "Marinated Olives"},
            {"qty": "as needed", "item": "Crackers — 2 types"},
            {"qty": "as needed", "item": "Dips", "prep": "hummus + capsicum"},
            {"qty": "as needed", "item": "Nuts", "prep": "marcona or roasted mix"},
        ],
        "method_steps": [
            "Line box with greaseproof, build height back-left to low front-right.",
            "Small pots for dips, ramekins for olives, cheese flags for IDs.",
        ],
        "service": [
            "Transport flat; include tongs and napkins count.",
        ],
        "note": "Cross-train with charcuterie board spec for overlap.",
    },
    {
        "id": "platter-ham-cheese-croissants",
        "name": "Ham & Cheese Croissants Platter",
        "subtitle": "Baked · Butter Glaze",
        "type": "Platter",
        "course": "Platter",
        "protein": ["pork", "dairy"],
        "diet": [],
        "method": "Bake",
        "yield": "12 serves (12 croissants)",
        "label": "Ham Cheese Croissant",
        "elements": ["Croissant", "Ham", "Cheese"],
        "ingredients": [
            {"qty": "12", "item": "Butter Croissants", "prep": "split"},
            {"qty": "300 g", "item": "Leg Ham", "prep": "thin"},
            {"qty": "200 g", "item": "Swiss Cheese", "prep": "sliced"},
            {"qty": "50 g", "item": "Butter", "prep": "melted brush"},
        ],
        "method_steps": [
            "Fill croissants, brush tops, bake 180°C 8m until cheese melts and pastry gold.",
            "Cool 5m before platter so cheese sets.",
        ],
        "service": [
            "Warm or room temp per client; label GF if using GF croissant line.",
        ],
        "note": None,
    },
    {
        "id": "platter-sandwiches-standard",
        "name": "Sandwich Platter",
        "subtitle": "Chef Selection Fills",
        "type": "Platter",
        "course": "Platter",
        "protein": ["chicken", "pork"],
        "diet": [],
        "method": "Assemble",
        "yield": "12 serves",
        "label": "Sandwich Platter",
        "elements": ["Bread", "Fills", "Garnish"],
        "ingredients": [
            {"qty": "2 loaves", "item": "Pullman or Multigrain", "prep": "crust on or off per spec"},
            {"qty": "as needed", "item": "Protein Fills", "prep": "chicken egg ham tuna rotation"},
            {"qty": "as needed", "item": "Butter & Mayo"},
            {"qty": "1 punnet", "item": "Lettuce & Tomato", "prep": "service side"},
        ],
        "method_steps": [
            "Build finger sandwiches 3 fingers per serve, wrap cling until 1h before service.",
            "Cut diagonal, pin with pick, arrange colour-balanced on platter.",
        ],
        "service": [
            "Include dietary flags if mixed box.",
        ],
        "note": None,
    },
    {
        "id": "platter-wraps-premium",
        "name": "Premium Filled Wraps Platter",
        "subtitle": "12 Gourmet Wraps",
        "type": "Platter",
        "course": "Platter",
        "protein": ["chicken", "beef"],
        "diet": [],
        "method": "Assemble",
        "yield": "12 wraps",
        "label": "Wrap Platter",
        "elements": ["Tortilla", "Fills", "Sauce"],
        "ingredients": [
            {"qty": "12 large", "item": "Tortilla Wraps"},
            {"qty": "as needed", "item": "Protein & Salad Fills", "prep": "chef mix"},
            {"qty": "200 ml", "item": "Aioli or Ranch", "prep": "line inside"},
        ],
        "method_steps": [
            "Tight roll, seam down, wrap tight in glad, chill 30m, slice bias into pinwheels or halves per client.",
        ],
        "service": [
            "Cut fresh — do not hold sliced >2h.",
        ],
        "note": None,
    },
    {
        "id": "platter-filled-brioche-rolls",
        "name": "Filled Brioche Rolls Platter",
        "subtitle": "Cold Protein Fills",
        "type": "Platter",
        "course": "Platter",
        "protein": ["chicken", "pork"],
        "diet": [],
        "method": "Assemble",
        "yield": "12 serves",
        "label": "Brioche Rolls",
        "elements": ["Brioche Roll", "Fill", "Leaf"],
        "ingredients": [
            {"qty": "12", "item": "Brioche Hot Dog Rolls", "prep": "split"},
            {"qty": "as needed", "item": "Cold Cuts & Slaw", "prep": "per run sheet"},
        ],
        "method_steps": [
            "Butter inside lightly, layer protein + slaw, close and wrap until service.",
        ],
        "service": [
            "Halve on bias for display.",
        ],
        "note": None,
    },
    {
        "id": "platter-roast-beef-beetroot-relish",
        "name": "Roast Beef & Beetroot Balsamic Platter",
        "subtitle": "Sliced · Relish",
        "type": "Platter",
        "course": "Platter",
        "protein": ["beef"],
        "diet": ["Gluten-Free"],
        "method": "Assemble",
        "yield": "12 serves",
        "label": "Beef Platter",
        "elements": ["Roast Beef", "Relish", "Bread optional"],
        "ingredients": [
            {"qty": "1.5 kg", "item": "Roast Beef — Rare side", "prep": "sliced thin"},
            {"qty": "400 g", "item": "Beetroot Balsamic Relish", "prep": "from batch"},
            {"qty": "optional", "item": "GF Bread", "prep": "side basket"},
        ],
        "method_steps": [
            "Slice beef to order if possible; else slice 3mm, shingle on tray, relish in ramekin centre.",
        ],
        "service": [
            "Tongs for beef, spoon for relish.",
        ],
        "note": None,
    },
    {
        "id": "platter-dietary-grazing",
        "name": "Dietary Grazing Platter",
        "subtitle": "GF · DF · Vegan · Egg-friendly Build",
        "type": "Platter",
        "course": "Platter",
        "protein": [],
        "diet": ["Vegan", "Gluten-Free", "Dairy-Free"],
        "method": "Assemble",
        "yield": "1 platter 4–6",
        "label": "Dietary Grazing",
        "elements": ["Veg Crudités", "Hummus", "GF Crackers", "Fruit", "Nuts"],
        "ingredients": [
            {"qty": "as needed", "item": "Veg Sticks & Cherry Tomato"},
            {"qty": "300 g", "item": "Hummus — DF"},
            {"qty": "as needed", "item": "GF Crackers"},
            {"qty": "as needed", "item": "Seasonal Fruit"},
            {"qty": "150 g", "item": "Roasted Nuts", "prep": "no honey glaze for vegan"},
        ],
        "method_steps": [
            "Segregated board — no shared knives with standard grazing.",
            "Label clearly at 12 o'clock position.",
        ],
        "service": [
            "Confirm allergen brief 48h prior.",
        ],
        "note": "Funeral PDF dietary platter analogue.",
    },
]

WAVE_C = [
    {
        "id": "corporate-savoury-croissants",
        "name": "Savoury Filled Croissants",
        "subtitle": "Chef Breakfast Fills",
        "type": "Component",
        "course": "Prep",
        "protein": ["chicken", "pork", "dairy"],
        "diet": [],
        "method": "Bake",
        "yield": "12 pieces minimum order",
        "label": "Savoury Croissants",
        "elements": ["Croissant", "Savoury Fill"],
        "ingredients": [
            {"qty": "12", "item": "Butter Croissants", "prep": "split"},
            {"qty": "as needed", "item": "Fill Selection", "prep": "egg bacon cheese / ham cheese / spinach feta"},
        ],
        "method_steps": [
            "Fill, egg wash seam, bake 180°C until cheese melts and pastry hot through.",
        ],
        "service": [
            "Box by the dozen for corporate morning tea.",
        ],
        "note": "Minimum 12 per PDF; GST ex per venue pricing sheet.",
    },
    {
        "id": "corporate-sweet-croissants",
        "name": "Sweet Filled Croissants",
        "subtitle": "Chef Sweet Fills",
        "type": "Component",
        "course": "Prep",
        "protein": ["dairy"],
        "diet": ["Vegetarian"],
        "method": "Bake",
        "yield": "12 pieces minimum order",
        "label": "Sweet Croissants",
        "elements": ["Croissant", "Sweet Fill"],
        "ingredients": [
            {"qty": "12", "item": "Butter Croissants"},
            {"qty": "as needed", "item": "Sweet Fill", "prep": "blueberry coconut / tiramisu hazelnut examples"},
        ],
        "method_steps": [
            "Pipe fill into split croissant or proof filled croissant per pastry chef SOP.",
            "Dust icing sugar before send.",
        ],
        "service": [],
        "note": None,
    },
    {
        "id": "corporate-bircher-muesli-bowls",
        "name": "Mixed Bircher Muesli Bowls",
        "subtitle": "Yoghurt · Fruit",
        "type": "Component",
        "course": "Prep",
        "protein": ["dairy"],
        "diet": ["Vegetarian", "Gluten-Free"],
        "method": "Mix",
        "yield": "12 bowls",
        "label": "Bircher Bowls",
        "elements": ["Bircher", "Fruit", "Yoghurt"],
        "ingredients": [
            {"qty": "500 g", "item": "Rolled Oats — GF"},
            {"qty": "1 L", "item": "Apple Juice"},
            {"qty": "500 g", "item": "Greek Yoghurt"},
            {"qty": "200 ml", "item": "Honey"},
            {"qty": "1 kg", "item": "Seasonal Fruit", "prep": "diced"},
            {"qty": "200 g", "item": "Toasted Almonds"},
        ],
        "method_steps": [
            "Soak oats in juice overnight, fold yoghurt and honey morning-of.",
            "Top with fruit and nuts in compostable bowl with lid.",
        ],
        "service": [
            "Keep chilled chain <5°C until handover.",
        ],
        "note": None,
    },
    {
        "id": "corporate-chicken-caesar-bowl",
        "name": "Chicken Caesar Salad Bowl",
        "subtitle": "Cos · Parmesan · Dressing",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["chicken", "dairy"],
        "diet": ["Gluten-Free"],
        "method": "Mix",
        "yield": "12 bowls",
        "label": "Caesar Bowl",
        "elements": ["Cos", "Chicken", "Dressing", "Parmesan"],
        "ingredients": [
            {"qty": "4 heads", "item": "Baby Cos", "prep": "chiffonade"},
            {"qty": "1.5 kg", "item": "Chicken Breast", "prep": "grilled slice"},
            {"qty": "400 ml", "item": "Caesar Dressing", "prep": "house or quality bought GF"},
            {"qty": "200 g", "item": "Parmesan", "prep": "shaved"},
            {"qty": "200 g", "item": "Bacon Bits", "prep": "optional"},
        ],
        "method_steps": [
            "Layer cos in bowl, chicken, dressing, parmesan, bacon if using.",
            "Hold cold; dress not more than 20m before send to avoid wilt.",
        ],
        "service": [],
        "note": None,
    },
    {
        "id": "corporate-lamb-fattoush-bowl",
        "name": "Lamb Fattoush Salad Bowl",
        "subtitle": "Herb Dressing · Pita Chip",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["lamb"],
        "diet": ["Dairy-Free"],
        "method": "Mix",
        "yield": "12 bowls",
        "label": "Fattoush Bowl",
        "elements": ["Lamb", "Salad", "Pita", "Dressing"],
        "ingredients": [
            {"qty": "1.2 kg", "item": "Lamb Backstrap", "prep": "seared rare, sliced"},
            {"qty": "mixed", "item": "Tomato Cucumber Radish Herbs", "prep": "diced salad"},
            {"qty": "6 pieces", "item": "Lebanese Bread", "prep": "toasted chips GF off if needed"},
            {"qty": "300 ml", "item": "Sumac Dressing", "prep": "olive oil lemon sumac garlic"},
        ],
        "method_steps": [
            "Dress salad lightly, top lamb, finish pita chips on top for crunch at send.",
        ],
        "service": [],
        "note": None,
    },
    {
        "id": "corporate-mediterranean-chicken-bowl",
        "name": "Mediterranean Chicken Bowl",
        "subtitle": "Pita · Tzatziki · Salad",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["chicken", "dairy"],
        "diet": ["Gluten-Free"],
        "method": "Assemble",
        "yield": "12 bowls",
        "label": "Med Chicken Bowl",
        "elements": ["Chicken", "Salad", "Pita", "Tzatziki"],
        "ingredients": [
            {"qty": "1.5 kg", "item": "Chicken Thigh", "prep": "grilled shawarma spice"},
            {"qty": "mixed", "item": "Med Salad", "prep": "cucumber tomato onion parsley"},
            {"qty": "12", "item": "Mini GF Pita"},
            {"qty": "400 g", "item": "Labneh Tzatziki", "prep": "from house batch"},
        ],
        "method_steps": [
            "Portion tzatziki in dip well, salad base, sliced chicken, pita on side.",
        ],
        "service": [],
        "note": "Uses labneh tzatziki house card for dip.",
    },
    {
        "id": "corporate-beef-lasagne-side-salad",
        "name": "Beef Lasagne with Side Salad",
        "subtitle": "Bake · Garden Salad",
        "type": "Tapas",
        "course": "Tapas",
        "protein": ["beef", "dairy"],
        "diet": [],
        "method": "Bake",
        "yield": "12 serves",
        "label": "Lasagne Lunch",
        "elements": ["Lasagne", "Garden Salad", "Dressing"],
        "ingredients": [
            {"qty": "2 trays", "item": "Beef Lasagne", "prep": "large cut 12 portions"},
            {"qty": "mixed", "item": "Garden Salad Leaves"},
            {"qty": "200 ml", "item": "Balsamic Dressing"},
        ],
        "method_steps": [
            "Reheat lasagne covered 160°C until centre 75°C, rest 10m before portion.",
            "Dress salad in separate container.",
        ],
        "service": [
            "Two-compartment box if takeaway.",
        ],
        "note": None,
    },
    {
        "id": "corporate-breakfast-wraps",
        "name": "Breakfast Wraps",
        "subtitle": "Bacon Egg Cheese Hash Relish",
        "type": "Component",
        "course": "Prep",
        "protein": ["pork", "dairy"],
        "diet": [],
        "method": "Grill",
        "yield": "12 wraps",
        "label": "Breakfast Wrap",
        "elements": ["Tortilla", "Fill", "Relish"],
        "ingredients": [
            {"qty": "12 large", "item": "Tortilla"},
            {"qty": "12", "item": "Hash Browns", "prep": "crispy"},
            {"qty": "12", "item": "Eggs", "prep": "scrambled or fried"},
            {"qty": "300 g", "item": "Bacon", "prep": "crisp"},
            {"qty": "200 g", "item": "Cheese", "prep": "melted in wrap"},
            {"qty": "150 g", "item": "Tomato Relish"},
        ],
        "method_steps": [
            "Warm tortilla, centre fills, fold burrito style, toast seam on press until marked.",
        ],
        "service": [],
        "note": None,
    },
    {
        "id": "corporate-gourmet-filled-cookies",
        "name": "Gourmet Filled Cookies",
        "subtitle": "Chef Selection",
        "type": "Bakery",
        "course": "Dessert",
        "protein": ["dairy"],
        "diet": ["Vegetarian"],
        "method": "Bake",
        "yield": "24 cookies",
        "label": "Filled Cookies",
        "elements": ["Cookie", "Ganache or Buttercream"],
        "ingredients": [
            {"qty": "24", "item": "Large Cookies", "prep": "baked base"},
            {"qty": "as needed", "item": "Fillings", "prep": "salted caramel / choc ganache"},
        ],
        "method_steps": [
            "Sandwich or thumbprint fill day-of so biscuit stays snap.",
        ],
        "service": [],
        "note": None,
    },
    {
        "id": "corporate-mixed-sandwiches",
        "name": "Mixed Filled Sandwiches",
        "subtitle": "Chef Selection",
        "type": "Platter",
        "course": "Platter",
        "protein": ["chicken", "pork"],
        "diet": [],
        "method": "Assemble",
        "yield": "12 serves",
        "label": "Mixed Sandwiches",
        "elements": ["Bread", "Fills"],
        "ingredients": [
            {"qty": "2 loaves", "item": "Mixed Bread", "prep": "white multigrain"},
            {"qty": "as needed", "item": "Protein & Salad Fills", "prep": "rotation"},
        ],
        "method_steps": [
            "Finger sandwich spec 3 per serve, crustless optional per client.",
        ],
        "service": [],
        "note": None,
    },
    {
        "id": "corporate-roast-veg-salad-bowl",
        "name": "Roasted Vegetable Salad Bowl",
        "subtitle": "Leaves · Dressing",
        "type": "Tapas",
        "course": "Tapas",
        "protein": [],
        "diet": ["Vegan", "Gluten-Free", "Dairy-Free"],
        "method": "Roast + Mix",
        "yield": "12 bowls",
        "label": "Roast Veg Bowl",
        "elements": ["Roast Vegetables", "Leaves", "Dressing"],
        "ingredients": [
            {"qty": "3 kg", "item": "Roast Veg Mix", "prep": "pumpkin capsicum zucchini red onion"},
            {"qty": "2 bags", "item": "Mixed Leaves"},
            {"qty": "300 ml", "item": "Balsamic Vinaigrette", "prep": "DF"},
        ],
        "method_steps": [
            "Roast veg 200°C until caramelised, cool slightly.",
            "Bowl: leaves, warm veg, drizzle dressing at send.",
        ],
        "service": [],
        "note": None,
    },
]
